# Generated by Django 4.2.3 on 2023-07-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='content',
            new_name='aprašymas',
        ),
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='title',
            new_name='pavadinimas',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='description',
            new_name='aprašymas',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='photo',
            new_name='nuotraukas',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='name',
            new_name='pavadinimas',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='elektroninis_pastas',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_service',
            new_name='norima_paslauga',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='vartotojas',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='services',
            new_name='paslauga',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_time',
            new_name='rezervuotas_laikas',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='vartotojas',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='address',
            new_name='adresas',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='pets_type',
            new_name='augintinio_tipas',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='pets_numbers',
            new_name='augintinių_skaičius',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='time_choice',
            new_name='galimas_laikas',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='time',
            new_name='laikas',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='preferred_service',
            new_name='norima_paslauga',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='user',
            new_name='vartotojas',
        ),
    ]
