# Generated by Django 4.2.3 on 2023-07-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_content_aboutcontent_aprašymas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vartotojas',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='vartotojas',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='vartotojas',
            new_name='user',
        ),
    ]
