# Generated by Django 4.2.3 on 2023-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_vartotojas_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='aprašymas',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='pavadinimas',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='aprašymas',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='nuotraukas',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='petservice',
            old_name='pavadinimas',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='norima_paslauga',
            new_name='desired_service',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='elektroninis_pastas',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='rezervuotas_laikas',
            new_name='reserve_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='paslauga',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='adresas',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='norima_paslauga',
            new_name='desired_service',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='augintinių_skaičius',
            new_name='num_of_pets',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='augintinio_tipas',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='reservetime',
            old_name='laikas',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reservetime',
            name='galimas_laikas',
        ),
        migrations.AddField(
            model_name='reservetime',
            name='time_choice',
            field=models.CharField(choices=[('08:00', '08:00 AM'), ('08:30', '08:30 AM'), ('09:00', '09:00 AM'), ('09:30', '09:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('13:00', '13:00 PM'), ('13:30', '13:30 PM'), ('14:00', '14:00 PM'), ('14:30', '14:30 PM'), ('15:00', '15:00 PM'), ('15:30', '15:30 PM'), ('16:00', '16:00 PM'), ('16:30', '16:30 PM'), ('17:00', '17:00 PM'), ('17:30', '17:30 PM'), ('18:00', '18:00 PM'), ('18:30', '18:30 PM'), ('19:00', '19:00 PM'), ('19:30', '19:30 PM')], default='08:00', max_length=5),
        ),
    ]
