# Generated by Django 4.2.3 on 2023-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_aprašymas_aboutcontent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
