# Generated by Django 4.2.3 on 2023-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_reserved_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetime',
            name='desired_service',
        ),
        migrations.AddField(
            model_name='reservetime',
            name='desired_service',
            field=models.ManyToManyField(blank=True, to='home.petservice'),
        ),
    ]
